### ISSUE TITLE
fdamp set incorrectly when imead==0

### ISSUE THREAD

**Issue by steven-murray** [alexander-mead/HMcode-old#2]
In the `fdamp` function, towards the end, you have `if (fdamp<1e-3) fdamp=1e-3`, however, when `imead=0`, fdamp should be zero, and therefore gets changed to 1e-3 here. Changing to `if (fdamp<1e-3.and.fdamp>0) fdamp=1e-3` should fix it?

**Comment by alexander-mead** [comment]
Hi Steven,

Ah, okay, yes, you're right. Without your fix one gets a tiny amount of
damping in the two-halo term even when doing the standard halomodel
calculation, which I suppose may make code comparisons more difficult. This
is a hangover from previous versions where I had caught extreme values of
fdamp in a different way.

I've moved those IF statements in the fdamp function so that they only
apply if imead=1 and so that fdamp is exactly zero otherwise. This will
change when I next upload to Git.

Cheers,
Alex

**Comment by steven-murray** [comment]
Awesome. Cheers.
